/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.marcart.redesbayesianas.interfaz;

import javax.swing.ButtonGroup;

/**
 *
 * @author mario
 */
public class VistaPrincipal extends javax.swing.JFrame {
    ControladorVistaPrincipal controlador;
    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        this.controlador = ControladorVistaPrincipal.getInstancia();
        
        ButtonGroup grupoobesidad = new ButtonGroup();
        grupoobesidad.add(radio_obesidadsi);
        grupoobesidad.add(radio_obesidadno);
        grupoobesidad.add(radio_obesidadnsnc);
        radio_obesidadnsnc.setSelected(true);
        
        ButtonGroup grupoembarazo = new ButtonGroup();
        grupoembarazo.add(radio_embarazosi);
        grupoembarazo.add(radio_embarazono);
        grupoembarazo.add(radio_embarazonsnc);
        radio_embarazonsnc.setSelected(true);
        
        ButtonGroup grupoantecedentescancer = new ButtonGroup();
        grupoantecedentescancer.add(radio_antecedentescancersi);
        grupoantecedentescancer.add(radio_antecedentescancerno);
        grupoantecedentescancer.add(radio_antecedentescancernsnc);
        radio_antecedentescancernsnc.setSelected(true);
        
        ButtonGroup grupocontaminantesquimicos = new ButtonGroup();
        grupocontaminantesquimicos.add(radio_contaminantesquimicossi);
        grupocontaminantesquimicos.add(radio_contaminantesquimicosno);
        grupocontaminantesquimicos.add(radio_contaminantesquimicosnsnc);
        radio_contaminantesquimicosnsnc.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        check_oxigenobajo = new javax.swing.JCheckBox();
        check_trombosis = new javax.swing.JCheckBox();
        check_cianosis = new javax.swing.JCheckBox();
        check_tosesputo = new javax.swing.JCheckBox();
        check_taquicardia = new javax.swing.JCheckBox();
        check_fiebre = new javax.swing.JCheckBox();
        check_tossangre = new javax.swing.JCheckBox();
        check_dolortoracico = new javax.swing.JCheckBox();
        check_tosseca = new javax.swing.JCheckBox();
        check_disnea = new javax.swing.JCheckBox();
        check_perdidapeso = new javax.swing.JCheckBox();
        check_sudoraciones = new javax.swing.JCheckBox();
        check_broncoespasmo = new javax.swing.JCheckBox();
        check_faltaapetito = new javax.swing.JCheckBox();
        check_insuficienciarenal = new javax.swing.JCheckBox();
        radio_obesidadsi = new javax.swing.JRadioButton();
        radio_obesidadno = new javax.swing.JRadioButton();
        label_obesidad = new javax.swing.JLabel();
        radio_obesidadnsnc = new javax.swing.JRadioButton();
        label_embarazo = new javax.swing.JLabel();
        radio_embarazosi = new javax.swing.JRadioButton();
        radio_embarazono = new javax.swing.JRadioButton();
        radio_embarazonsnc = new javax.swing.JRadioButton();
        label_antecedentescancer = new javax.swing.JLabel();
        radio_antecedentescancersi = new javax.swing.JRadioButton();
        radio_antecedentescancerno = new javax.swing.JRadioButton();
        radio_antecedentescancernsnc = new javax.swing.JRadioButton();
        label_contaminantesquimicos = new javax.swing.JLabel();
        radio_contaminantesquimicossi = new javax.swing.JRadioButton();
        radio_contaminantesquimicosno = new javax.swing.JRadioButton();
        radio_contaminantesquimicosnsnc = new javax.swing.JRadioButton();
        label_contactoneumonia = new javax.swing.JLabel();
        radio_contactoneumoniasi = new javax.swing.JRadioButton();
        radio_contactoneumoniano = new javax.swing.JRadioButton();
        radio_contactoneumoniansnc = new javax.swing.JRadioButton();
        label_gripe = new javax.swing.JLabel();
        label_viajeasia = new javax.swing.JLabel();
        label_contactotuberculosis = new javax.swing.JLabel();
        label_fumador = new javax.swing.JLabel();
        label_antecedentesasma = new javax.swing.JLabel();
        label_exposicionalergenos = new javax.swing.JLabel();
        label_antecedentesepoc = new javax.swing.JLabel();
        radio_gripesi = new javax.swing.JRadioButton();
        radio_gripeno = new javax.swing.JRadioButton();
        radio_gripensnc = new javax.swing.JRadioButton();
        radio_viajeasiasi = new javax.swing.JRadioButton();
        radio_viajeasiano = new javax.swing.JRadioButton();
        radio_viajeasiansnc = new javax.swing.JRadioButton();
        radio_contactotuberculosissi = new javax.swing.JRadioButton();
        radio_contactotuberculosisno = new javax.swing.JRadioButton();
        radio_contactotuberculosisnsnc = new javax.swing.JRadioButton();
        radio_fumadorsi = new javax.swing.JRadioButton();
        radio_fumadorno = new javax.swing.JRadioButton();
        radio_fumadornsnc = new javax.swing.JRadioButton();
        radio_exposicionalergenossi = new javax.swing.JRadioButton();
        radio_exposicionalergenosno = new javax.swing.JRadioButton();
        radio_exposicionalergenosnsnc = new javax.swing.JRadioButton();
        radio_antecedentesepocsi = new javax.swing.JRadioButton();
        radio_antecedentesepocno = new javax.swing.JRadioButton();
        radio_antecedentesepocnsnc = new javax.swing.JRadioButton();
        radio_antecedentesasmasi = new javax.swing.JRadioButton();
        radio_antecedentesasmano = new javax.swing.JRadioButton();
        radio_antecedentesasmansnc = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Cargar otra red");

        jLabel1.setText("Red cargada por defeto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Observaciones del paciente");

        jLabel4.setText("Enfermedad mas posible");

        check_oxigenobajo.setText("Oxígeno bajo en sangre");

        check_trombosis.setText("Trombosis");

        check_cianosis.setText("Cianosis");

        check_tosesputo.setText("Tos con esputo");

        check_taquicardia.setText("Taquicardia");

        check_fiebre.setText("Fiebre");

        check_tossangre.setText("Tos con sangre");

        check_dolortoracico.setText("Dolor torácico");

        check_tosseca.setText("Tos seca");
        check_tosseca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_tossecaActionPerformed(evt);
            }
        });

        check_disnea.setText("Disnea");

        check_perdidapeso.setText("Pérdida de peso");

        check_sudoraciones.setText("Sudoraciones");

        check_broncoespasmo.setText("Broncoesmpasmo");

        check_faltaapetito.setText("Falta de apetito");

        check_insuficienciarenal.setText("Insuficiencia renal");

        radio_obesidadsi.setText("Sí");
        radio_obesidadsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_obesidadsiActionPerformed(evt);
            }
        });

        radio_obesidadno.setText("No");

        label_obesidad.setText("Obesidad");

        radio_obesidadnsnc.setText("NS/NC");

        label_embarazo.setText("Embarazo");

        radio_embarazosi.setText("Sí");
        radio_embarazosi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_embarazosiActionPerformed(evt);
            }
        });

        radio_embarazono.setText("No");

        radio_embarazonsnc.setText("NS/NC");

        label_antecedentescancer.setText("Antecedentes Cáncer");

        radio_antecedentescancersi.setText("Sí");
        radio_antecedentescancersi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_antecedentescancersiActionPerformed(evt);
            }
        });

        radio_antecedentescancerno.setText("No");

        radio_antecedentescancernsnc.setText("NS/NC");

        label_contaminantesquimicos.setText("Contacto con contaminantes químicos ");

        radio_contaminantesquimicossi.setText("Sí");
        radio_contaminantesquimicossi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_contaminantesquimicossiActionPerformed(evt);
            }
        });

        radio_contaminantesquimicosno.setText("No");

        radio_contaminantesquimicosnsnc.setText("NS/NC");

        label_contactoneumonia.setText("Contacto con neumonía");

        radio_contactoneumoniasi.setText("Sí");
        radio_contactoneumoniasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_contactoneumoniasiActionPerformed(evt);
            }
        });

        radio_contactoneumoniano.setText("No");

        radio_contactoneumoniansnc.setText("NS/NC");

        label_gripe.setText("Tiene gripe");

        label_viajeasia.setText("Viaje a Asia");

        label_contactotuberculosis.setText("Contacto con tuberculosis");

        label_fumador.setText("Fumador");

        label_antecedentesasma.setText("Antecedentes de asma");

        label_exposicionalergenos.setText("Exposición a alérgenos");

        label_antecedentesepoc.setText("Antecedentes EPOC");

        radio_gripesi.setText("Sí");
        radio_gripesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_gripesiActionPerformed(evt);
            }
        });

        radio_gripeno.setText("No");

        radio_gripensnc.setText("NS/NC");

        radio_viajeasiasi.setText("Sí");
        radio_viajeasiasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_viajeasiasiActionPerformed(evt);
            }
        });

        radio_viajeasiano.setText("No");

        radio_viajeasiansnc.setText("NS/NC");

        radio_contactotuberculosissi.setText("Sí");
        radio_contactotuberculosissi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_contactotuberculosissiActionPerformed(evt);
            }
        });

        radio_contactotuberculosisno.setText("No");

        radio_contactotuberculosisnsnc.setText("NS/NC");

        radio_fumadorsi.setText("Sí");
        radio_fumadorsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_fumadorsiActionPerformed(evt);
            }
        });

        radio_fumadorno.setText("No");

        radio_fumadornsnc.setText("NS/NC");

        radio_exposicionalergenossi.setText("Sí");
        radio_exposicionalergenossi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_exposicionalergenossiActionPerformed(evt);
            }
        });

        radio_exposicionalergenosno.setText("No");

        radio_exposicionalergenosnsnc.setText("NS/NC");

        radio_antecedentesepocsi.setText("Sí");
        radio_antecedentesepocsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_antecedentesepocsiActionPerformed(evt);
            }
        });

        radio_antecedentesepocno.setText("No");

        radio_antecedentesepocnsnc.setText("NS/NC");

        radio_antecedentesasmasi.setText("Sí");
        radio_antecedentesasmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_antecedentesasmasiActionPerformed(evt);
            }
        });

        radio_antecedentesasmano.setText("No");

        radio_antecedentesasmansnc.setText("NS/NC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(515, 515, 515)
                        .addComponent(jLabel4)
                        .addContainerGap(99, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(label_contaminantesquimicos)
                            .addComponent(label_contactoneumonia)
                            .addComponent(label_gripe)
                            .addComponent(label_viajeasia)
                            .addComponent(label_contactotuberculosis)
                            .addComponent(label_fumador)
                            .addComponent(label_antecedentesasma)
                            .addComponent(label_exposicionalergenos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(label_antecedentescancer)
                                            .addGap(79, 79, 79))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(label_embarazo, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(label_obesidad, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addComponent(label_antecedentesepoc))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_antecedentesepocsi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_antecedentesepocno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_antecedentesepocnsnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_obesidadsi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_obesidadno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_obesidadnsnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_contactoneumoniasi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_contactoneumoniano)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_contactoneumoniansnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_contaminantesquimicossi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_contaminantesquimicosno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_contaminantesquimicosnsnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_antecedentescancersi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_antecedentescancerno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_antecedentescancernsnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_embarazosi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_embarazono)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_embarazonsnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_gripesi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_gripeno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_gripensnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_viajeasiasi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_viajeasiano)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_viajeasiansnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_contactotuberculosissi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_contactotuberculosisno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_contactotuberculosisnsnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_fumadorsi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_fumadorno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_fumadornsnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_antecedentesasmasi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_antecedentesasmano)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_antecedentesasmansnc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radio_exposicionalergenossi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_exposicionalergenosno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radio_exposicionalergenosnsnc)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(check_insuficienciarenal)
                            .addComponent(check_faltaapetito)
                            .addComponent(check_broncoespasmo)
                            .addComponent(check_taquicardia)
                            .addComponent(check_fiebre)
                            .addComponent(check_tossangre)
                            .addComponent(check_dolortoracico)
                            .addComponent(check_tosseca)
                            .addComponent(check_disnea)
                            .addComponent(check_perdidapeso)
                            .addComponent(check_sudoraciones)
                            .addComponent(check_tosesputo)
                            .addComponent(check_oxigenobajo)
                            .addComponent(check_trombosis)
                            .addComponent(check_cianosis))
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(check_oxigenobajo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_trombosis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_cianosis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_tosesputo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_taquicardia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_fiebre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_tossangre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_dolortoracico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_tosseca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_disnea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_perdidapeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_sudoraciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_broncoespasmo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(check_faltaapetito))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_obesidad)
                            .addComponent(radio_obesidadno)
                            .addComponent(radio_obesidadsi)
                            .addComponent(radio_obesidadnsnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_embarazo)
                            .addComponent(radio_embarazosi)
                            .addComponent(radio_embarazono)
                            .addComponent(radio_embarazonsnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_antecedentescancer)
                            .addComponent(radio_antecedentescancersi)
                            .addComponent(radio_antecedentescancerno)
                            .addComponent(radio_antecedentescancernsnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_contaminantesquimicos)
                            .addComponent(radio_contaminantesquimicossi)
                            .addComponent(radio_contaminantesquimicosno)
                            .addComponent(radio_contaminantesquimicosnsnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_contactoneumonia)
                            .addComponent(radio_contactoneumoniasi)
                            .addComponent(radio_contactoneumoniano)
                            .addComponent(radio_contactoneumoniansnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_gripe)
                            .addComponent(radio_gripesi)
                            .addComponent(radio_gripeno)
                            .addComponent(radio_gripensnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_viajeasia)
                            .addComponent(radio_viajeasiasi)
                            .addComponent(radio_viajeasiano)
                            .addComponent(radio_viajeasiansnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_contactotuberculosis)
                            .addComponent(radio_contactotuberculosissi)
                            .addComponent(radio_contactotuberculosisno)
                            .addComponent(radio_contactotuberculosisnsnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_fumador)
                            .addComponent(radio_fumadorsi)
                            .addComponent(radio_fumadorno)
                            .addComponent(radio_fumadornsnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_antecedentesasma)
                            .addComponent(radio_antecedentesasmasi)
                            .addComponent(radio_antecedentesasmano)
                            .addComponent(radio_antecedentesasmansnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_exposicionalergenos)
                            .addComponent(radio_exposicionalergenossi)
                            .addComponent(radio_exposicionalergenosno)
                            .addComponent(radio_exposicionalergenosnsnc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_antecedentesepoc)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radio_antecedentesepocsi)
                                .addComponent(radio_antecedentesepocno)
                                .addComponent(radio_antecedentesepocnsnc)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(check_insuficienciarenal)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_tossecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_tossecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_tossecaActionPerformed

    private void radio_obesidadsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_obesidadsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_obesidadsiActionPerformed

    private void radio_embarazosiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_embarazosiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_embarazosiActionPerformed

    private void radio_antecedentescancersiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_antecedentescancersiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_antecedentescancersiActionPerformed

    private void radio_contaminantesquimicossiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_contaminantesquimicossiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_contaminantesquimicossiActionPerformed

    private void radio_contactoneumoniasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_contactoneumoniasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_contactoneumoniasiActionPerformed

    private void radio_gripesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_gripesiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_gripesiActionPerformed

    private void radio_viajeasiasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_viajeasiasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_viajeasiasiActionPerformed

    private void radio_contactotuberculosissiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_contactotuberculosissiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_contactotuberculosissiActionPerformed

    private void radio_fumadorsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_fumadorsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_fumadorsiActionPerformed

    private void radio_exposicionalergenossiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_exposicionalergenossiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_exposicionalergenossiActionPerformed

    private void radio_antecedentesepocsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_antecedentesepocsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_antecedentesepocsiActionPerformed

    private void radio_antecedentesasmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_antecedentesasmasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radio_antecedentesasmasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check_broncoespasmo;
    private javax.swing.JCheckBox check_cianosis;
    private javax.swing.JCheckBox check_disnea;
    private javax.swing.JCheckBox check_dolortoracico;
    private javax.swing.JCheckBox check_faltaapetito;
    private javax.swing.JCheckBox check_fiebre;
    private javax.swing.JCheckBox check_insuficienciarenal;
    private javax.swing.JCheckBox check_oxigenobajo;
    private javax.swing.JCheckBox check_perdidapeso;
    private javax.swing.JCheckBox check_sudoraciones;
    private javax.swing.JCheckBox check_taquicardia;
    private javax.swing.JCheckBox check_tosesputo;
    private javax.swing.JCheckBox check_tossangre;
    private javax.swing.JCheckBox check_tosseca;
    private javax.swing.JCheckBox check_trombosis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel label_antecedentesasma;
    private javax.swing.JLabel label_antecedentescancer;
    private javax.swing.JLabel label_antecedentesepoc;
    private javax.swing.JLabel label_contactoneumonia;
    private javax.swing.JLabel label_contactotuberculosis;
    private javax.swing.JLabel label_contaminantesquimicos;
    private javax.swing.JLabel label_embarazo;
    private javax.swing.JLabel label_exposicionalergenos;
    private javax.swing.JLabel label_fumador;
    private javax.swing.JLabel label_gripe;
    private javax.swing.JLabel label_obesidad;
    private javax.swing.JLabel label_viajeasia;
    private javax.swing.JRadioButton radio_antecedentesasmano;
    private javax.swing.JRadioButton radio_antecedentesasmansnc;
    private javax.swing.JRadioButton radio_antecedentesasmasi;
    private javax.swing.JRadioButton radio_antecedentescancerno;
    private javax.swing.JRadioButton radio_antecedentescancernsnc;
    private javax.swing.JRadioButton radio_antecedentescancersi;
    private javax.swing.JRadioButton radio_antecedentesepocno;
    private javax.swing.JRadioButton radio_antecedentesepocnsnc;
    private javax.swing.JRadioButton radio_antecedentesepocsi;
    private javax.swing.JRadioButton radio_contactoneumoniano;
    private javax.swing.JRadioButton radio_contactoneumoniansnc;
    private javax.swing.JRadioButton radio_contactoneumoniasi;
    private javax.swing.JRadioButton radio_contactotuberculosisno;
    private javax.swing.JRadioButton radio_contactotuberculosisnsnc;
    private javax.swing.JRadioButton radio_contactotuberculosissi;
    private javax.swing.JRadioButton radio_contaminantesquimicosno;
    private javax.swing.JRadioButton radio_contaminantesquimicosnsnc;
    private javax.swing.JRadioButton radio_contaminantesquimicossi;
    private javax.swing.JRadioButton radio_embarazono;
    private javax.swing.JRadioButton radio_embarazonsnc;
    private javax.swing.JRadioButton radio_embarazosi;
    private javax.swing.JRadioButton radio_exposicionalergenosno;
    private javax.swing.JRadioButton radio_exposicionalergenosnsnc;
    private javax.swing.JRadioButton radio_exposicionalergenossi;
    private javax.swing.JRadioButton radio_fumadorno;
    private javax.swing.JRadioButton radio_fumadornsnc;
    private javax.swing.JRadioButton radio_fumadorsi;
    private javax.swing.JRadioButton radio_gripeno;
    private javax.swing.JRadioButton radio_gripensnc;
    private javax.swing.JRadioButton radio_gripesi;
    private javax.swing.JRadioButton radio_obesidadno;
    private javax.swing.JRadioButton radio_obesidadnsnc;
    private javax.swing.JRadioButton radio_obesidadsi;
    private javax.swing.JRadioButton radio_viajeasiano;
    private javax.swing.JRadioButton radio_viajeasiansnc;
    private javax.swing.JRadioButton radio_viajeasiasi;
    // End of variables declaration//GEN-END:variables
}
